"""Deterministic construction of the frozen scenario fixtures.

Every scenario's count vectors are built here from explicit category
specifications -- never sampled -- so the clean panel and the mutant-probe
panel are bit-reproducible. Randomness appears only in the coverage campaign,
whose seeds are recorded separately in `fixtures/seeds.json`.

Expected dispositions in this file are DECLARED by the implementer from the
preregistration's decision rules before the sound reference is run against
them. They are not copied from any target. `harness.checks.panel` then verifies
that the sound reference reproduces every declared expectation; a disagreement
is a finding to adjudicate, not something to overwrite.

Exact point expectations are generated by `harness.oracle`, which is the
independent expected-answer generator, and are additionally cross-checked
against `fixtures/anchors/hand-anchors-v1.0.json`.
"""

import copy
import json
import os

from . import roster
from .oracle import core, sample as smp

K = 10
CELLS = ("00", "A0", "0B", "AB")

from .workspace import ROOT
FIXTURE_ROOT = os.path.join(ROOT, "fixtures")

DEFAULT_CONFIG = {"alpha": {"primary": 0.05, "c4": 0.05, "c5": 0.05},
                  "d_near": 0.9}

CLEAN_VALIDITY = {"provenance": True, "cache": True, "schema": True,
                  "local_lens": True, "refusal": True}


# ---------------------------------------------------------------------------
# Count-vector construction helpers
# ---------------------------------------------------------------------------

def counts(spec, n):
    """Build a count vector from {category: weight} with total exactly n.

    Weights are apportioned by largest remainder so the total is exact and the
    construction is deterministic.
    """
    items = sorted(spec.items())
    total_weight = sum(w for _c, w in items)
    raw = [(c, n * w / float(total_weight)) for c, w in items]
    base = [(c, int(v)) for c, v in raw]
    remainder = n - sum(v for _c, v in base)
    order = sorted(range(len(raw)), key=lambda i: (-(raw[i][1] - base[i][1]),
                                                   raw[i][0]))
    allocated = dict(base)
    for i in order[:remainder]:
        allocated[raw[i][0]] += 1
    vector = [0] * K
    for category, value in allocated.items():
        vector[category - 1] = value
    if sum(vector) != n:
        raise AssertionError("count construction failed for %r at n=%d" % (spec, n))
    return vector


def uniform_over(categories, n):
    return counts({c: 1 for c in categories}, n)


def point(category, n):
    return counts({category: 1}, n)


def specimen(specimen_id, c00, ca0, c0b, cab):
    return {"id": specimen_id,
            "cells": {"00": {"counts": list(c00)}, "A0": {"counts": list(ca0)},
                      "0B": {"counts": list(c0b)}, "AB": {"counts": list(cab)}}}


def repeat_specimens(prefix, builder, how_many):
    """Build a specimen list using CANONICAL frozen-roster identifiers.

    The mapping from role index to identifier is positional and bijective
    (harness/roster.py), so every scenario's meaning is preserved exactly:
    position i still carries the same distribution, which is what the
    leave-one-out order and the first-three/last-three splits depend on. Only
    the label changes.
    """
    naming = roster.semantic_id if prefix == "S" else roster.mechanical_id
    return [specimen(naming(i), *builder(i)) for i in range(how_many)]


def make_light(light_id, semantic, mechanical, validity=None):
    return {"id": light_id,
            "validity": dict(validity or CLEAN_VALIDITY),
            "semantic_specimens": copy.deepcopy(semantic),
            "mechanical_specimens": copy.deepcopy(mechanical)}


def make_payload(lights, analysis_id=None, config=None):
    return {"schema_version": "blackbox.ordinal.ordinal-counts.v0.1",
            "analysis_id": analysis_id,
            "config": copy.deepcopy(config or DEFAULT_CONFIG),
            "lights": lights}


def uniform_payload(analysis_id, semantic, mechanical, validity=None, config=None):
    """Three lights with identical content -- the usual topology-exercise form."""
    lights = [make_light("L%d" % i, semantic, mechanical, validity)
              for i in (1, 2, 3)]
    return make_payload(lights, analysis_id, config)


# ---------------------------------------------------------------------------
# Standard building blocks
# ---------------------------------------------------------------------------

def sep_high(n):
    """00 cell fully above the 0B cell: P0 = 1 (anchor A05)."""
    return point(10, n)


def sep_low(n):
    return point(1, n)


def dispersed_high(n):
    """00 cell spread over 7..10: P0 = 1 against `dispersed_low`, C ~ 0.25."""
    return uniform_over([7, 8, 9, 10], n)


def dispersed_low(n):
    return uniform_over([1, 2, 3, 4], n)


def mid_point(n, category=6):
    return point(category, n)


def mid_dispersed(n):
    return uniform_over([5, 6, 7, 8], n)


# ---------------------------------------------------------------------------
# Oracle expectations
# ---------------------------------------------------------------------------

def oracle_expectations(payload):
    """Exact point-estimate expectations for every light in a payload."""
    d_near = payload["config"]["d_near"]
    out = {"semantic_lights": [], "mechanical_lights": []}
    for light in payload["lights"]:
        for key, target in (("semantic_specimens", "semantic_lights"),
                            ("mechanical_specimens", "mechanical_lights")):
            cells_list = [{c: s["cells"][c]["counts"] for c in CELLS}
                          for s in light[key]]
            truth = smp.light_truth(cells_list, d_near=d_near)
            entry = {
                "light_id": light["id"],
                "P0_bar": core.to_exact_string(truth["P0_bar"]),
                "I_P_bar": core.to_exact_string(truth["I_P_bar"]),
                "Q_bar": core.to_exact_string(truth["Q_bar"]),
                "specimens": [],
            }
            for specimen_input, metrics in zip(light[key], truth["specimens"]):
                entry["specimens"].append({
                    "id": specimen_input["id"],
                    "P0": core.to_exact_string(metrics["P0"]),
                    "PA": core.to_exact_string(metrics["PA"]),
                    "I_P": core.to_exact_string(metrics["I_P"]),
                    "W0": core.to_exact_string(metrics["W0"]),
                    "L0": core.to_exact_string(metrics["L0"]),
                    "T0": core.to_exact_string(metrics["T0"]),
                    "WA": core.to_exact_string(metrics["WA"]),
                    "LA": core.to_exact_string(metrics["LA"]),
                    "TA": core.to_exact_string(metrics["TA"]),
                    "delta0": core.to_exact_string(metrics["delta0"]),
                    "deltaA": core.to_exact_string(metrics["deltaA"]),
                    "I_delta": core.to_exact_string(metrics["I_delta"]),
                    "p_floor_A0": core.to_exact_string(metrics["p_floor_A0"]),
                    "K_A": core.to_exact_string(metrics["K_A"]),
                    "G": core.to_exact_string(metrics["G"]),
                    "K_Q": core.to_exact_string(metrics["K_Q"]),
                    "G_Q": core.to_exact_string(metrics["G_Q"]),
                    "Q": core.to_exact_string(metrics["Q"]),
                    "collision": {c: core.to_exact_string(metrics["collision"][c])
                                  for c in CELLS},
                    "degeneracy": dict(metrics["degeneracy"]),
                })
            out[target].append(entry)
    return out


STUDY_CANDIDATE_N = (8, 10, 12, 16, 20, 30)


def classify_n(payload):
    """Operator decision D5: separate study-candidate N from topology exercises.

    The class is COMPUTED from the payload's actual cell totals, never
    asserted, so a scenario cannot be mislabelled by an author oversight.
    """
    totals = set()
    for light in payload["lights"]:
        for key in ("semantic_specimens", "mechanical_specimens"):
            for specimen in light[key]:
                for cell in CELLS:
                    totals.add(sum(specimen["cells"][cell]["counts"]))
    outside = sorted(t for t in totals if t not in STUDY_CANDIDATE_N)
    if outside:
        return {
            "n_class": "TOPOLOGY_EXERCISE_ONLY_NOT_STUDY_EVIDENCE",
            "replicate_totals": sorted(totals),
            "totals_outside_candidate_set": outside,
            "study_candidate_N": list(STUDY_CANDIDATE_N),
            "usable_as_study_evidence": False,
            "rationale": (
                "Included only as a synthetic harness "
                "topology/branch-coverage. The registered 0.05 equivalence "
                "margins are not resolvable at study N under any "
                "distribution-free construction, which preregistration 3.4 "
                "anticipates, so some decision branches have no sound case at "
                "candidate N. This scenario is NOT evidence about study "
                "behaviour at any candidate N and plays no part in N "
                "selection; the coverage campaign is that evidence."),
        }
    return {
        "n_class": "STUDY_CANDIDATE_N",
        "replicate_totals": sorted(totals),
        "totals_outside_candidate_set": [],
        "study_candidate_N": list(STUDY_CANDIDATE_N),
        "usable_as_study_evidence": True,
        "rationale": "every cell total lies in the study candidate set",
    }


def scenario(scenario_id, description, payload, expected, strength,
             contract_refs, notes=None, family="clean", target="analyze"):
    entry = {
        "scenario_id": scenario_id,
        "family": family,
        "target": target,
        "description": description,
        "contract_refs": contract_refs,
        "assertion_strength": strength,
        "notes": notes or "",
        "payload": payload,
        "expected": expected,
        "oracle_point_expectations": oracle_expectations(payload),
    }
    entry["replicate_classification"] = classify_n(payload)
    return entry


def light_expect(c1, rng, c2, c4, a_l, light_ids=("L1", "L2", "L3")):
    return [{"light_id": lid, "c1": c1, "range": rng, "c2": c2, "c4": c4,
             "A_l": a_l} for lid in light_ids]


def mech_expect(c5, light_ids=("L1", "L2", "L3")):
    return [{"light_id": lid, "c5": c5} for lid in light_ids]


def cross_expect(a_all, a_vector=(True, True, True)):
    return {"A_all": a_all, "A_vector": list(a_vector),
            "c3": "WITHHELD_NOT_IMPLEMENTED", "pooled_verdict_absent": True}


# ---------------------------------------------------------------------------
# The clean-reference panel
# ---------------------------------------------------------------------------

def build_clean_panel():
    panel = []

    # --- CL-01: full attenuation chain supported at a study-candidate N ------
    n = 30
    sem = repeat_specimens("S", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 6)
    mech = repeat_specimens("M", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 4)
    panel.append(scenario(
        "CL-01-CHAIN-SUPPORTED-N30",
        "Complete separation with A present halving discrimination: C1, range, "
        "validity and C2 all clear, so A_l and A_all are earned. C4 is opened "
        "but its concentration capacity is exhausted by degenerate baselines, "
        "which must withhold C4 without touching C2 (anchors A12, A19).",
        uniform_payload("CL-01", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "C4_CONCENTRATION_CAPACITY_NOT_CLEARED", True),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(True)},
        "REFERENCE_ONLY", ["contract 5", "contract 6", "prereg 4", "prereg 12.3"],
        "P0 = 1 and PA = 1/2 exactly for every specimen, so I_P = 1/2."))

    # --- CL-02: all ties, interior --------------------------------------------
    n = 30
    sem = repeat_specimens("S", lambda i: (
        point(5, n), point(5, n), point(5, n), point(5, n)), 6)
    mech = repeat_specimens("M", lambda i: (
        point(5, n), point(5, n), point(5, n), point(5, n)), 4)
    panel.append(scenario(
        "CL-02-ALL-TIES-INTERIOR",
        "Every cell is the same interior point mass. Anchor A01 fixes W=0, L=0, "
        "T=1, PS=1/2 and I_P=0. The registered outcome is INDETERMINATE at this "
        "N, and every interval must retain positive width: degeneracy alone is "
        "not an inference-engine failure (contract 7).",
        uniform_payload("CL-02", sem, mech),
        {"semantic_lights": light_expect(
            "INDETERMINATE", "RANGE_CLEARED", "NOT_OPENED_C1_NOT_SUPPORTED",
            "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_NOT_ELIGIBLE"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["contract 7", "prereg 12.2"],
        "Degeneracy flag EMPIRICALLY_DEGENERATE on all four cells; "
        "INFERENCE_ENGINE_FAILURE must NOT be emitted."))

    # --- CL-03: floor point masses -------------------------------------------
    n = 30
    sem = repeat_specimens("S", lambda i: (
        point(1, n), point(1, n), point(1, n), point(1, n)), 6)
    mech = repeat_specimens("M", lambda i: (
        point(1, n), point(1, n), point(1, n), point(1, n)), 4)
    panel.append(scenario(
        "CL-03-ALL-TIES-FLOOR",
        "All four cells degenerate at the score floor. p_floor,A0 = 1 gives "
        "K_A = 1/2 by anchor A08, so the G point estimate is "
        "0.5 - (0.5 - 0.15) = +0.15; but the registered disposition is on the "
        "INTERVAL for G (anchor A11), and at N=30 that interval crosses zero, "
        "so the correct answer is RANGE_INDETERMINATE and the light is "
        "RANGE_NOT_CLEARED. A target returning RANGE_ADEQUATE here is applying "
        "a point-estimate rule where an interval rule is registered.",
        uniform_payload("CL-03", sem, mech),
        {"semantic_lights": light_expect(
            "INDETERMINATE", "RANGE_NOT_CLEARED", "NOT_OPENED_C1_NOT_SUPPORTED",
            "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_NOT_ELIGIBLE"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["contract 7", "prereg 5.1", "anchor A11"]))

    # --- CL-04: point masses at different categories, complete separation -----
    n = 30
    sem = repeat_specimens("S", lambda i: (
        point(10, n), point(10, n), point(1, n), point(1, n)), 6)
    mech = repeat_specimens("M", lambda i: (
        point(10, n), point(10, n), point(1, n), point(1, n)), 4)
    panel.append(scenario(
        "CL-04-SEPARATION-NO-INTERACTION",
        "Complete separation in both cell pairs: P0 = PA = 1 and I_P = 0 exactly "
        "(anchor A05). C1 is supported, the range gate clears because "
        "p_floor,A0 = 0 gives K_A = 1, and C2 is correctly NOT supported. At "
        "N=30 the C2 interval is too wide for equivalence, so INDETERMINATE.",
        uniform_payload("CL-04", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "INDETERMINATE", "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_INDETERMINATE"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["contract 5", "prereg 4"],
        "The key clean property: a true zero interaction must not be reported "
        "as attenuation."))

    # --- CL-05: C2 equivalently absent at high N ------------------------------
    n = 2000
    sem = repeat_specimens("S", lambda i: (
        point(10, n), point(10, n), point(1, n), point(1, n)), 6)
    mech = repeat_specimens("M", lambda i: (
        point(10, n), point(10, n), point(1, n), point(1, n)), 4)
    panel.append(scenario(
        "CL-05-C2-EQUIVALENTLY-ABSENT",
        "The same true zero interaction as CL-04, resolved: at N=2000 the C2 "
        "interval lies wholly inside [-0.05, +0.05] and both equivalence guards "
        "pass, so EQUIVALENTLY_ABSENT is the registered outcome.",
        uniform_payload("CL-05", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "EQUIVALENTLY_ABSENT",
            "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_EQUIVALENTLY_ABSENT"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["contract 6", "prereg 4"],
        "N=2000 is a deliberate topology-exercise size outside the study "
        "candidate set {8,10,12,16,20,30}: the registered 0.05 equivalence "
        "margin is not resolvable at study N under any distribution-free "
        "construction, which the preregistration itself anticipates in 3.4. "
        "The study-N behaviour of this branch is exercised in the coverage "
        "campaign, not here."))

    # --- CL-06: C1 equivalently absent ---------------------------------------
    n = 2000
    sem = repeat_specimens("S", lambda i: (
        point(5, n), point(5, n), point(5, n), point(5, n)), 6)
    mech = repeat_specimens("M", lambda i: (
        point(5, n), point(5, n), point(5, n), point(5, n)), 4)
    panel.append(scenario(
        "CL-06-C1-EQUIVALENTLY-ABSENT",
        "True P0 = 1/2 resolved at N=2000: the C1 interval lies wholly inside "
        "[0.45, 0.55] and both C1 equivalence guards pass. B was not ordinally "
        "resolved without A, so C2 is never opened.",
        uniform_payload("CL-06", sem, mech),
        {"semantic_lights": light_expect(
            "EQUIVALENTLY_ABSENT", "RANGE_CLEARED",
            "NOT_OPENED_C1_NOT_SUPPORTED", "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_NOT_ELIGIBLE"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["prereg 4", "prereg 13"],
        "Same topology-exercise N rationale as CL-05."))

    # --- CL-07: range not cleared (one floor-limited specimen) ----------------
    n = 2000

    def cl07(i):
        if i == 0:
            # A0 pinned at the floor: p_floor = 1, K_A = 1/2, G = -0.35
            return (point(10, n), point(1, n), point(1, n), point(1, n))
        return (point(10, n), mid_point(n), point(1, n), mid_point(n))

    sem = repeat_specimens("S", cl07, 6)
    mech = repeat_specimens("M", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 4)
    panel.append(scenario(
        "CL-07-RANGE-NOT-CLEARED",
        "One of the six semantic specimens is floor-limited (A0 entirely at the "
        "score floor, K_A = 1/2 by anchor A08). The all-six rule then withholds "
        "the corpus-level C2 disposition for the light, while C1 remains "
        "supported and every unit effect is still reported.",
        uniform_payload("CL-07", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_NOT_CLEARED", "RANGE_NOT_CLEARED",
            "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(False, (False, False, False))},
        "ABSOLUTE", ["contract 6", "prereg 5.3"],
        "Structural: no numeric value may produce an C2 support or equivalence "
        "declaration for a light whose all-six range gate fails."))

    # --- CL-08: instrument validity not cleared -------------------------------
    n = 30
    sem = repeat_specimens("S", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 6)
    mech = repeat_specimens("M", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 4)
    broken = dict(CLEAN_VALIDITY)
    broken["provenance"] = False
    lights = [make_light("L1", sem, mech, broken),
              make_light("L2", sem, mech),
              make_light("L3", sem, mech)]
    panel.append(scenario(
        "CL-08-VALIDITY-NOT-CLEARED",
        "Numerically identical to CL-01 except that light L1 fails the "
        "provenance validity flag. L1's confirmatory dispositions must be "
        "withheld rather than converted into a scientific null, A_L1 is false, "
        "and A_all is therefore false while L2 and L3 remain supported.",
        make_payload(lights, "CL-08"),
        {"semantic_lights": [
            {"light_id": "L1", "c1": "INSTRUMENT_VALIDITY_NOT_CLEARED",
             "range": "RANGE_CLEARED", "c2": "INSTRUMENT_VALIDITY_NOT_CLEARED",
             "c4": "C4_NOT_OPENED", "A_l": False},
            {"light_id": "L2", "c1": "SUPPORTED", "range": "RANGE_CLEARED",
             "c2": "SUPPORTED", "c4": "C4_CONCENTRATION_CAPACITY_NOT_CLEARED",
             "A_l": True},
            {"light_id": "L3", "c1": "SUPPORTED", "range": "RANGE_CLEARED",
             "c2": "SUPPORTED", "c4": "C4_CONCENTRATION_CAPACITY_NOT_CLEARED",
             "A_l": True}],
         "mechanical_lights": [
             {"light_id": "L1", "c5": "CONTROL_NOT_ELIGIBLE"},
             {"light_id": "L2", "c5": "CONTROL_ATTENUATION_SUPPORTED"},
             {"light_id": "L3", "c5": "CONTROL_ATTENUATION_SUPPORTED"}],
         "cross_light": cross_expect(False, (False, True, True))},
        "ABSOLUTE", ["contract 6", "prereg 12.3", "prereg 13"],
        "Structural gate: a validity failure blocks A_l for any numeric values "
        "(anchor A19)."))

    # --- CL-09: C4 supported ---------------------------------------------------
    n = 2000
    sem = repeat_specimens("S", lambda i: (
        dispersed_high(n), mid_point(n), dispersed_low(n), mid_point(n)), 6)
    mech = repeat_specimens("M", lambda i: (
        dispersed_high(n), mid_point(n), dispersed_low(n), mid_point(n)), 4)
    panel.append(scenario(
        "CL-09-C4-SUPPORTED",
        "Dispersed baselines (collision about 1/4) with concentrated A-present "
        "cells (collision 1) leave ample concentration capacity and produce "
        "Q about 3/4. With A_l supported, C4 earns "
        "GENERAL_RESOLUTION_LOSS_SUPPORTED.",
        uniform_payload("CL-09", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "GENERAL_RESOLUTION_LOSS_SUPPORTED", True),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(True)},
        "REFERENCE_ONLY", ["prereg 4 C4", "prereg 5.5"]))

    # --- CL-10: C4 equivalently absent ----------------------------------------
    n = 2000
    sem = repeat_specimens("S", lambda i: (
        dispersed_high(n), mid_dispersed(n), dispersed_low(n), mid_dispersed(n)), 6)
    mech = repeat_specimens("M", lambda i: (
        dispersed_high(n), mid_dispersed(n), dispersed_low(n), mid_dispersed(n)), 4)
    panel.append(scenario(
        "CL-10-C4-EQUIVALENTLY-ABSENT",
        "Attenuation is present (I_P = 1/2) while every cell has the same "
        "dispersion, so both component contrasts and Q are exactly zero. C4 "
        "must return GENERAL_RESOLUTION_LOSS_EQUIVALENTLY_ABSENT without "
        "disturbing the supported C2.",
        uniform_payload("CL-10", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "GENERAL_RESOLUTION_LOSS_EQUIVALENTLY_ABSENT", True),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(True)},
        "REFERENCE_ONLY", ["prereg 4 C4", "contract 9 FALSE-EQUIVALENCE"]))

    # --- CL-11: ceiling-concentrated baselines, C4 capacity withheld ----------
    n = 2000

    def cl11(i):
        return (point(10, n), mid_point(n), point(1, n), mid_point(n))

    sem = repeat_specimens("S", cl11, 6)
    mech = repeat_specimens("M", cl11, 4)
    panel.append(scenario(
        "CL-11-CEILING-BASELINE-C4-CAPACITY",
        "The named FALSE-EQUIVALENCE ceiling case: 00 is ceiling-concentrated "
        "and 0B floor-concentrated, so K_Q = 0 and G_Q = -0.10 by anchor A12. "
        "C4 must be withheld for want of capacity and must NOT be reported as "
        "equivalently absent, and it must not protect, overwrite, rescue or "
        "invalidate the supported C2.",
        uniform_payload("CL-11", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "C4_CONCENTRATION_CAPACITY_NOT_CLEARED", True),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(True)},
        "ABSOLUTE", ["contract 9 FALSE-EQUIVALENCE", "amendment 3", "prereg 5.5"]))

    # --- CL-12 / CL-13: C4 non-interference pair ------------------------------
    n = 2000
    sem_a = repeat_specimens("S", lambda i: (
        dispersed_high(n), point(6, n), dispersed_low(n), point(6, n)), 6)
    mech_a = repeat_specimens("M", lambda i: (
        dispersed_high(n), point(6, n), dispersed_low(n), point(6, n)), 4)
    sem_b = repeat_specimens("S", lambda i: (
        dispersed_high(n), mid_dispersed(n), dispersed_low(n),
        mid_dispersed(n)), 6)
    mech_b = repeat_specimens("M", lambda i: (
        dispersed_high(n), mid_dispersed(n), dispersed_low(n),
        mid_dispersed(n)), 4)
    for suffix, sem_v, mech_v, c4 in (
            ("A", sem_a, mech_a, "GENERAL_RESOLUTION_LOSS_SUPPORTED"),
            ("B", sem_b, mech_b,
             "GENERAL_RESOLUTION_LOSS_EQUIVALENTLY_ABSENT")):
        panel.append(scenario(
            "CL-12-C4-NONINTERFERENCE-%s" % suffix,
            "Half of the anchor A19 non-interference pair. Variants A and B "
            "hold P0, PA, I_P, p_floor,A0 and G exactly equal -- both A-present "
            "cells share one distribution, so PA = 1/2 either way -- while "
            "moving the concentration far enough to flip C4 from SUPPORTED to "
            "EQUIVALENTLY_ABSENT. C1, range and C2 must therefore be identical "
            "across the pair. This is the operative test that C4 cannot "
            "protect, overwrite, rescue or invalidate C2.",
            uniform_payload("CL-12%s" % suffix, sem_v, mech_v),
            {"semantic_lights": light_expect(
                "SUPPORTED", "RANGE_CLEARED", "SUPPORTED", c4, True),
             "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
             "cross_light": cross_expect(True)},
            "ABSOLUTE", ["amendment 3", "anchor A19"],
            "Paired scenario; the pairwise identity assertion lives in "
            "harness.checks.topology_checks."))

    # --- CL-14: mixed light vector --------------------------------------------
    n = 30
    strong = repeat_specimens("S", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 6)
    neutral = repeat_specimens("S", lambda i: (
        point(5, n), point(5, n), point(5, n), point(5, n)), 6)
    mech_strong = repeat_specimens("M", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 4)
    mech_neutral = repeat_specimens("M", lambda i: (
        point(5, n), point(5, n), point(5, n), point(5, n)), 4)
    broken = dict(CLEAN_VALIDITY)
    broken["cache"] = False
    lights = [make_light("L1", strong, mech_strong),
              make_light("L2", neutral, mech_neutral),
              make_light("L3", strong, mech_strong, broken)]
    panel.append(scenario(
        "CL-14-MIXED-LIGHT-VECTOR",
        "Three materially different lights: L1 supported, L2 indeterminate, L3 "
        "withheld for a cache validity failure. A_all must be false, all three "
        "per-light dispositions must be reported, and no pooled verdict may "
        "replace the vector (anchor A20).",
        make_payload(lights, "CL-14"),
        {"semantic_lights": [
            {"light_id": "L1", "c1": "SUPPORTED", "range": "RANGE_CLEARED",
             "c2": "SUPPORTED", "c4": "C4_CONCENTRATION_CAPACITY_NOT_CLEARED",
             "A_l": True},
            {"light_id": "L2", "c1": "INDETERMINATE", "range": "RANGE_CLEARED",
             "c2": "NOT_OPENED_C1_NOT_SUPPORTED", "c4": "C4_NOT_OPENED",
             "A_l": False},
            {"light_id": "L3", "c1": "INSTRUMENT_VALIDITY_NOT_CLEARED",
             "range": "RANGE_CLEARED", "c2": "INSTRUMENT_VALIDITY_NOT_CLEARED",
             "c4": "C4_NOT_OPENED", "A_l": False}],
         "mechanical_lights": [
             {"light_id": "L1", "c5": "CONTROL_ATTENUATION_SUPPORTED"},
             {"light_id": "L2", "c5": "CONTROL_NOT_ELIGIBLE"},
             {"light_id": "L3", "c5": "CONTROL_NOT_ELIGIBLE"}],
         "cross_light": cross_expect(False, (True, False, False))},
        "ABSOLUTE", ["contract 6", "anchor A20", "prereg 13"]))

    # --- CL-15: C1 recurrence guard withholds support -------------------------
    n = 2000

    def cl15(i):
        # three strongly positive specimens, three exactly neutral:
        # P0_bar = 3/4 clears 0.70, but only 3 of 6 centred effects are positive
        if i < 3:
            return (point(10, n), point(6, n), point(1, n), point(6, n))
        return (point(5, n), point(6, n), point(5, n), point(6, n))

    sem = repeat_specimens("S", cl15, 6)
    mech = repeat_specimens("M", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 4)
    panel.append(scenario(
        "CL-15-C1-GUARD-NOT-MET",
        "The C1 aggregate interval clears 0.70 (P0_bar = 3/4) but only three of "
        "six centred specimen effects are strictly positive, so the frozen "
        "recurrence guard withholds support. The registered outcome is "
        "INDETERMINATE_GUARD_NOT_MET, never SUPPORTED (anchor A18).",
        uniform_payload("CL-15", sem, mech),
        {"semantic_lights": light_expect(
            "INDETERMINATE_GUARD_NOT_MET", "RANGE_CLEARED",
            "NOT_OPENED_C1_NOT_SUPPORTED", "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(False, (False, False, False))},
        "ABSOLUTE", ["contract 6", "prereg 4", "anchor A18"]))

    # --- CL-16: C2 heterogeneity guard withholds equivalence ------------------
    n = 2000

    def cl16(i):
        # P0 = 0.85 everywhere: 00 at the ceiling, 0B is 70% floor / 30% ceiling
        # so W = 0.7, T = 0.3 and P0 = 0.7 + 0.15 = 0.85.
        # First three specimens: AB is 30% floor / 70% at category 6 against an
        # A0 point mass at 6, giving PA = 0.3 + 0.35 = 0.65 and I_P = +0.20.
        # Last three: AB is a floor point mass, giving PA = 1 and I_P = -0.15.
        cell_00 = point(10, n)
        cell_0b = counts({1: 7, 10: 3}, n)
        cell_a0 = point(6, n)
        if i < 3:
            return (cell_00, cell_a0, cell_0b, counts({1: 3, 6: 7}, n))
        return (cell_00, cell_a0, cell_0b, point(1, n))

    sem = repeat_specimens("S", cl16, 6)
    mech = repeat_specimens("M", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 4)
    panel.append(scenario(
        "CL-16-C2-HETEROGENEITY-NOT-CLEARED",
        "Sign-cancelling specimen interactions (three at +0.20, three at -0.15) "
        "whose equal-weight mean, 0.025, sits inside the equivalence region. "
        "Both frozen equivalence guards fail: the corpus contains an effect at "
        "or above +0.15 together with one at or below -0.15, and two "
        "leave-one-out means fall outside the band. The registered outcome is "
        "HETEROGENEITY_NOT_CLEARED, not practical absence.",
        uniform_payload("CL-16", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "HETEROGENEITY_NOT_CLEARED",
            "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["contract 6", "contract 8", "prereg 4"]))

    # --- CL-17: near-degenerate cells with unobserved rare categories ---------
    n = 20
    sem = repeat_specimens("S", lambda i: (
        counts({10: 19, 9: 1}, n), counts({6: 19, 5: 1}, n),
        counts({1: 19, 2: 1}, n), counts({6: 19, 7: 1}, n)), 6)
    mech = repeat_specimens("M", lambda i: (
        counts({10: 19, 9: 1}, n), counts({6: 19, 5: 1}, n),
        counts({1: 19, 2: 1}, n), counts({6: 19, 7: 1}, n)), 4)
    panel.append(scenario(
        "CL-17-NEAR-DEGENERATE-RARE-CATEGORY",
        "Near-point masses at N=20 with eight of ten categories unobserved. "
        "Every interval must stay non-degenerate and the cells must be flagged "
        "EMPIRICALLY_NEAR_DEGENERATE at the supplied d_near = 0.9 without any "
        "disposition consequence beyond reporting. C1 is supported, but at "
        "N=20 the capacity surplus G still straddles zero, so the all-six "
        "range gate correctly withholds the corpus-level C2 disposition.",
        uniform_payload("CL-17", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_NOT_CLEARED", "RANGE_NOT_CLEARED",
            "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_NOT_ELIGIBLE"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["contract 7", "prereg 12.2", "prereg 5.3"],
        "m_hat = 19/20 = 0.95 >= d_near = 0.9. The degeneracy flags must be "
        "reported and must not themselves change any disposition."))

    # --- CL-18: high-tie interior distributions -------------------------------
    n = 30
    sem = repeat_specimens("S", lambda i: (
        counts({7: 25, 8: 5}, n), counts({6: 25, 7: 5}, n),
        counts({7: 25, 6: 5}, n), counts({6: 25, 5: 5}, n)), 6)
    mech = repeat_specimens("M", lambda i: (
        counts({7: 25, 8: 5}, n), counts({6: 25, 7: 5}, n),
        counts({7: 25, 6: 5}, n), counts({6: 25, 5: 5}, n)), 4)
    panel.append(scenario(
        "CL-18-HIGH-TIE-INTERIOR",
        "Heavily overlapping interior distributions where ties dominate the "
        "cross-tabulation. This is the scenario that most sharply separates the "
        "registered tie-adjusted estimator from the two prohibited tie "
        "treatments recorded in anchor A14.",
        uniform_payload("CL-18", sem, mech),
        {"semantic_lights": light_expect(
            "INDETERMINATE", "RANGE_CLEARED", "NOT_OPENED_C1_NOT_SUPPORTED",
            "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_NOT_ELIGIBLE"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["contract 5", "contract 7"]))

    # --- CL-19: unequal cell totals, equal specimen weighting -----------------
    def cl19(i):
        big, small = 2000, 200
        if i % 2 == 0:
            return (point(10, big), point(6, big), point(1, big), point(6, big))
        return (point(10, small), point(6, small), point(1, small), point(6, small))

    sem = repeat_specimens("S", cl19, 6)
    mech = repeat_specimens("M", cl19, 4)
    panel.append(scenario(
        "CL-19-UNEQUAL-CELL-TOTALS",
        "Specimens carry 2000 and 200 calls alternately -- a ten-to-one "
        "imbalance. Each specimen's effect must receive weight exactly 1/6 "
        "regardless of replicate count; a call-weighted pool would give a "
        "different answer (anchor A13). The sizes are large enough that the "
        "range gate clears, so the imbalance rather than the capacity gate is "
        "the property under test.",
        uniform_payload("CL-19", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "C4_CONCENTRATION_CAPACITY_NOT_CLEARED", True),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(True)},
        "REFERENCE_ONLY", ["contract 5", "prereg 3.2"]))

    # --- CL-20: C5 control not eligible ---------------------------------------
    n = 30
    sem = repeat_specimens("S", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 6)
    mech = repeat_specimens("M", lambda i: (
        point(5, n), point(5, n), point(5, n), point(5, n)), 4)
    panel.append(scenario(
        "CL-20-C5-CONTROL-NOT-ELIGIBLE",
        "The mechanical controls show no standalone discrimination, so C5 is "
        "ineligible and receives CONTROL_NOT_ELIGIBLE. The four controls must "
        "not enter the six-specimen primary aggregate, which remains supported.",
        uniform_payload("CL-20", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "C4_CONCENTRATION_CAPACITY_NOT_CLEARED", True),
         "mechanical_lights": mech_expect("CONTROL_NOT_ELIGIBLE"),
         "cross_light": cross_expect(True)},
        "ABSOLUTE", ["contract 6", "prereg 5.6"]))

    # --- CL-21: equivalence near miss -----------------------------------------
    # N is chosen so the C2 half-width lands between the registered 0.05 margin
    # and a plausible widened 0.07 one: the scenario is INDETERMINATE under the
    # registered rule and would become EQUIVALENTLY_ABSENT only if the margin
    # were widened after seeing the near miss.
    n = 272
    sem = repeat_specimens("S", lambda i: (
        point(10, n), point(10, n), point(1, n), point(1, n)), 6)
    mech = repeat_specimens("M", lambda i: (
        point(10, n), point(10, n), point(1, n), point(1, n)), 4)
    panel.append(scenario(
        "CL-21-EQUIVALENCE-NEAR-MISS",
        "A true zero interaction resolved only to about +/-0.060 -- just "
        "outside the registered +/-0.05 equivalence region. The registered "
        "outcome is INDETERMINATE: practical absence has NOT been demonstrated, "
        "and the margin may not be widened because the preferred value is "
        "difficult to resolve (preregistration 3.4). This scenario exists so "
        "that the widened-margin defect has somewhere to show itself.",
        uniform_payload("CL-21", sem, mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "INDETERMINATE", "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_INDETERMINATE"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["contract 8", "contract 9 FALSE-EQUIVALENCE",
                           "prereg 3.4"],
        "Half-width lands in (0.05, 0.07); an engine reporting "
        "EQUIVALENTLY_ABSENT here has widened its margin after a near miss."))

    # --- CL-22: C1 equivalence heterogeneity guard ----------------------------
    n = 2000
    standard_mech = repeat_specimens("M", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 4)

    def cl22(i):
        # three specimens at P0 = 0.8, three at P0 = 0.2: the corpus mean is
        # exactly 0.5 and sits inside the equivalence region, but the corpus
        # contains opposing meaningful effects
        if i < 3:
            return (point(10, n), point(6, n), counts({1: 3, 10: 2}, n),
                    point(6, n))
        return (point(1, n), point(6, n), counts({1: 2, 10: 3}, n), point(6, n))

    panel.append(scenario(
        "CL-22-C1-HETEROGENEITY-NOT-CLEARED",
        "The C1 aggregate interval lies wholly inside [0.45, 0.55], but three "
        "specimens sit at P0 = 0.8 and three at P0 = 0.2. Both C1 equivalence "
        "guards fail: the corpus contains a centred effect at or above +0.20 "
        "together with one at or below -0.20, and the leave-one-out means "
        "leave the band. Practical absence must be withheld.",
        uniform_payload("CL-22", repeat_specimens("S", cl22, 6), standard_mech),
        {"semantic_lights": light_expect(
            "HETEROGENEITY_NOT_CLEARED", "RANGE_CLEARED",
            "NOT_OPENED_C1_NOT_SUPPORTED", "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(False, (False, False, False))},
        "REFERENCE_ONLY", ["prereg 4", "contract 8"]))

    # --- CL-23: C2 recurrence guard -------------------------------------------
    def cl23(i):
        # three specimens with I_P = 0.9, three with I_P = 0: the aggregate
        # clears 0.15 but only three of six interactions are positive
        if i < 3:
            return (point(10, n), point(6, n), point(1, n),
                    counts({6: 1, 10: 4}, n))
        return (point(10, n), point(6, n), point(1, n), point(1, n))

    panel.append(scenario(
        "CL-23-C2-GUARD-NOT-MET",
        "The C2 aggregate interval clears 0.15 but only three of six specimen "
        "interactions are strictly positive, so the frozen recurrence guard "
        "withholds support. The registered outcome is "
        "INDETERMINATE_GUARD_NOT_MET and the complete six-specimen vector is "
        "reported (anchor A18).",
        uniform_payload("CL-23", repeat_specimens("S", cl23, 6), standard_mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "INDETERMINATE_GUARD_NOT_MET",
            "C4_NOT_OPENED", False),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(False, (False, False, False))},
        "ABSOLUTE", ["contract 6", "prereg 4", "anchor A18"]))

    # --- CL-24: C4 indeterminate ----------------------------------------------
    def cl24(i):
        # baselines dispersed over four categories, A-present cells slightly
        # more concentrated: Q lands between the equivalence band and 0.10
        concentrated = counts({5: 45, 6: 25, 7: 20, 8: 10}, n)
        return (dispersed_high(n), concentrated, dispersed_low(n), concentrated)

    panel.append(scenario(
        "CL-24-C4-INDETERMINATE",
        "With A_l supported and the concentration capacity cleared, Q lands at "
        "about 0.065: the interval clears neither the 0.10 meaningful boundary "
        "nor the [-0.05, +0.05] equivalence band. The diagnostic had adequate "
        "measured capacity but remains inconclusive, so mechanism language is "
        "withheld.",
        uniform_payload("CL-24", repeat_specimens("S", cl24, 6),
                        repeat_specimens("M", cl24, 4)),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "GENERAL_RESOLUTION_LOSS_INDETERMINATE", True),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(True)},
        "REFERENCE_ONLY", ["prereg 4 C4", "prereg 13"]))

    # --- CL-25: C4 component guard --------------------------------------------
    def cl25(i):
        # q0 strongly positive, qB negative: the aggregate clears 0.10 but the
        # two component means have opposite signs
        return (dispersed_high(n), counts({6: 85, 7: 15}, n),
                uniform_over([1, 2], n),
                counts({5: 40, 6: 30, 7: 20, 8: 10}, n))

    panel.append(scenario(
        "CL-25-C4-GUARD-NOT-MET",
        "The C4 aggregate interval clears 0.10, but the two A-associated "
        "component contrasts have opposite signs, so the registered rule that "
        "their average may not conceal opposite-sign components withholds "
        "support. C2 is unaffected.",
        uniform_payload("CL-25", repeat_specimens("S", cl25, 6), standard_mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "C4_INDETERMINATE_GUARD_NOT_MET", True),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(True)},
        "REFERENCE_ONLY", ["prereg 4 C4"]))

    # --- CL-26: C4 equivalence heterogeneity guard ----------------------------
    def cl26(i):
        skewed_high = counts({7: 6, 8: 2, 9: 1, 10: 1}, n)
        skewed_low = counts({1: 6, 2: 2, 3: 1, 4: 1}, n)
        skewed_mid = counts({5: 6, 6: 2, 7: 1, 8: 1}, n)
        if i < 3:
            # C_A0 > C_00 and C_AB > C_0B: Q about +0.17
            return (dispersed_high(n), skewed_mid, dispersed_low(n), skewed_mid)
        # mirror image: Q about -0.17
        return (skewed_high, mid_dispersed(n), skewed_low, mid_dispersed(n))

    panel.append(scenario(
        "CL-26-C4-HETEROGENEITY-NOT-CLEARED",
        "Sign-cancelling specimen concentration contrasts whose mean sits "
        "inside the C4 equivalence band, with both component means also in "
        "band. The anti-cancellation guard fails because the corpus contains a "
        "Q at or above +0.10 together with one at or below -0.10, so C4 "
        "absence is not established.",
        uniform_payload("CL-26", repeat_specimens("S", cl26, 6), standard_mech),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "C4_HETEROGENEITY_NOT_CLEARED", True),
         "mechanical_lights": mech_expect("CONTROL_ATTENUATION_SUPPORTED"),
         "cross_light": cross_expect(True)},
        "REFERENCE_ONLY", ["prereg 4 C4"]))

    # --- CL-27: C5 control guards ---------------------------------------------
    strong_sem = repeat_specimens("S", lambda i: (
        sep_high(n), mid_point(n), sep_low(n), mid_point(n)), 6)

    def cl27a(i):
        if i < 2:
            return (point(10, n), point(6, n), point(1, n),
                    counts({6: 1, 10: 4}, n))
        return (point(10, n), point(6, n), point(1, n), point(1, n))

    panel.append(scenario(
        "CL-27-C5-GUARD-NOT-MET",
        "The mechanical-control interaction interval clears 0.15 but only two "
        "of four control interactions are strictly positive, failing the "
        "three-of-four recurrence rule. The control result is "
        "CONTROL_INDETERMINATE_GUARD_NOT_MET and the complete control vector "
        "is reported.",
        uniform_payload("CL-27", strong_sem, repeat_specimens("M", cl27a, 4)),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "C4_CONCENTRATION_CAPACITY_NOT_CLEARED", True),
         "mechanical_lights": mech_expect("CONTROL_INDETERMINATE_GUARD_NOT_MET"),
         "cross_light": cross_expect(True)},
        "ABSOLUTE", ["prereg 5.6", "prereg 13"]))

    # --- CL-28: C5 equivalence heterogeneity guard ----------------------------
    def cl28(i):
        # P0 = 0.75 throughout; two controls at I_P = +0.25, two at -0.25
        base = (counts({1: 1, 10: 1}, n))
        if i < 2:
            return (point(10, n), point(6, n), base, point(6, n))
        return (point(10, n), point(6, n), base, point(1, n))

    panel.append(scenario(
        "CL-28-C5-HETEROGENEITY-NOT-CLEARED",
        "The mechanical-control interaction interval lies inside the "
        "equivalence band, but the four controls split into two at +0.25 and "
        "two at -0.25. The registered opposing-meaningful-effect guard "
        "withholds control equivalence.",
        uniform_payload("CL-28", strong_sem, repeat_specimens("M", cl28, 4)),
        {"semantic_lights": light_expect(
            "SUPPORTED", "RANGE_CLEARED", "SUPPORTED",
            "C4_CONCENTRATION_CAPACITY_NOT_CLEARED", True),
         "mechanical_lights": mech_expect("CONTROL_HETEROGENEITY_NOT_CLEARED"),
         "cross_light": cross_expect(True)},
        "REFERENCE_ONLY", ["prereg 5.6"]))

    # Mark the scenarios whose cells are interior and non-degenerate, so the
    # interval-scaling check can run without tripping over the legitimate
    # 1/n shrinkage that exact boundary methods show at a point mass.
    for entry in panel:
        if entry["scenario_id"] in ("CL-09-C4-SUPPORTED",
                                    "CL-10-C4-EQUIVALENTLY-ABSENT",
                                    "CL-18-HIGH-TIE-INTERIOR"):
            entry["interval_scaling_eligible"] = True

    return panel


# ---------------------------------------------------------------------------
# Serialization
# ---------------------------------------------------------------------------

# ---------------------------------------------------------------------------
# The anchor-realization panel
# ---------------------------------------------------------------------------

def build_anchor_panel():
    """One payload whose specimens realize the hand-computed anchors directly.

    Amendment section 4 requires the oracle, the harness AND the sound
    reference each to be checked against the same immutable hand calculations.
    The oracle is checked symbolically in `harness.checks.anchor_checks`; this
    panel is how a *target* is checked, by embedding each anchor configuration
    as a real specimen and asserting the reported quantities against the values
    frozen in `docs/ANCHORS.md`.
    """
    semantic = [
        # A01: identical interior point masses -> W=0, L=0, T=1, PS=1/2
        specimen("sample-01", point(5, 30), point(5, 30), point(5, 30), point(5, 30)),
        # A05: complete separation one way, complete reverse separation the other
        specimen("sample-02", point(10, 30), point(1, 30), point(1, 30), point(10, 30)),
        # A07: balanced two-category 00 cell at n=4 -> C_hat = 1/3, not 1/2
        specimen("sample-03", counts({1: 1, 2: 1}, 4), point(6, 4),
                 point(3, 4), point(6, 4)),
        # A10: section 5.3 -- A0 at category 2, AB at category 1
        specimen("sample-04", point(10, 9), point(2, 9), point(1, 9), point(1, 9)),
        # A14: worked non-degenerate W/L/T case
        specimen("sample-05", counts({8: 2, 9: 1}, 3), point(6, 3),
                 counts({7: 1, 8: 1, 10: 1}, 3), point(6, 3)),
        # A08: p_floor,A0 = 2/5 -> K_A = 4/5 (and NOT the no-half-credit 3/5)
        specimen("sample-06", point(10, 10), counts({1: 4, 6: 6}, 10),
                 point(1, 10), point(6, 10)),
    ]
    mechanical = [
        # A09: point-mass collision equals one
        specimen("control-01", point(4, 7), point(4, 7), point(4, 7), point(4, 7)),
        # A12: degenerate baselines -> K_Q = 0, G_Q = -1/10
        specimen("control-02", point(10, 20), point(6, 20), point(1, 20), point(6, 20)),
        # A11: G exactly zero at p_floor = 2/5 and P0 = 19/20
        specimen("control-03", counts({10: 18, 1: 2}, 20), counts({1: 8, 6: 12}, 20),
                 point(1, 20), point(6, 20)),
        # A05 reverse separation at adjacent categories: PS = 1 without distance
        specimen("control-04", point(3, 12), point(6, 12), point(2, 12), point(6, 12)),
    ]

    payload = uniform_payload("AN-01", semantic, mechanical)

    assertions = [
        {"group": "semantic", "specimen": "sample-01", "field": "P0",
         "exact": "1/2", "anchor": "A01"},
        {"group": "semantic", "specimen": "sample-01", "field": "W0",
         "exact": "0/1", "anchor": "A01"},
        {"group": "semantic", "specimen": "sample-01", "field": "L0",
         "exact": "0/1", "anchor": "A01"},
        {"group": "semantic", "specimen": "sample-01", "field": "T0",
         "exact": "1/1", "anchor": "A01"},
        {"group": "semantic", "specimen": "sample-01", "field": "delta0",
         "exact": "0/1", "anchor": "A04"},
        {"group": "semantic", "specimen": "sample-02", "field": "P0",
         "exact": "1/1", "anchor": "A05"},
        {"group": "semantic", "specimen": "sample-02", "field": "PA",
         "exact": "0/1", "anchor": "A05"},
        {"group": "semantic", "specimen": "sample-02", "field": "delta0",
         "exact": "1/1", "anchor": "A04"},
        {"group": "semantic", "specimen": "sample-02", "field": "deltaA",
         "exact": "-1/1", "anchor": "A04"},
        {"group": "semantic", "specimen": "sample-03", "field": "collision.00",
         "exact": "1/3", "anchor": "A07",
         "prohibited": {"naive squared-proportion": "1/2"}},
        {"group": "semantic", "specimen": "sample-04", "field": "PA",
         "exact": "1/1", "anchor": "A10"},
        {"group": "semantic", "specimen": "sample-04", "field": "p_floor_A0",
         "exact": "0/1", "anchor": "A10"},
        {"group": "semantic", "specimen": "sample-04", "field": "K_A",
         "exact": "1/1", "anchor": "A10"},
        {"group": "semantic", "specimen": "sample-05", "field": "W0",
         "exact": "4/9", "anchor": "A14"},
        {"group": "semantic", "specimen": "sample-05", "field": "L0",
         "exact": "1/3", "anchor": "A14"},
        {"group": "semantic", "specimen": "sample-05", "field": "T0",
         "exact": "2/9", "anchor": "A14"},
        {"group": "semantic", "specimen": "sample-05", "field": "P0",
         "exact": "5/9", "anchor": "A14",
         "prohibited": {"ties discarded": "4/7", "ties as wins": "2/3"}},
        {"group": "semantic", "specimen": "sample-05", "field": "delta0",
         "exact": "1/9", "anchor": "A04"},
        {"group": "semantic", "specimen": "sample-05", "field": "collision.00",
         "exact": "1/3", "anchor": "A14"},
        {"group": "semantic", "specimen": "sample-06", "field": "p_floor_A0",
         "exact": "2/5", "anchor": "A08"},
        {"group": "semantic", "specimen": "sample-06", "field": "K_A",
         "exact": "4/5", "anchor": "A08",
         "prohibited": {"no floor half-credit": "3/5"}},
        {"group": "mechanical", "specimen": "control-01", "field": "collision.00",
         "exact": "1/1", "anchor": "A09"},
        {"group": "mechanical", "specimen": "control-02", "field": "K_Q",
         "exact": "0/1", "anchor": "A12"},
        {"group": "mechanical", "specimen": "control-02", "field": "G_Q",
         "exact": "-1/10", "anchor": "A12"},
        {"group": "mechanical", "specimen": "control-03", "field": "P0",
         "exact": "19/20", "anchor": "A11"},
        {"group": "mechanical", "specimen": "control-03", "field": "K_A",
         "exact": "4/5", "anchor": "A11"},
        {"group": "mechanical", "specimen": "control-03", "field": "G",
         "exact": "0/1", "anchor": "A11"},
        {"group": "mechanical", "specimen": "control-04", "field": "P0",
         "exact": "1/1", "anchor": "A05",
         "note": "separation at adjacent categories 3 over 2"},
    ]

    entry = {
        "scenario_id": "AN-01-HAND-ANCHOR-REALIZATION",
        "family": "anchors",
        "target": "analyze",
        "description": "Each specimen realizes one hand-computed anchor so that "
                       "a target can be checked directly against the immutable "
                       "hand calculations, not only against the oracle.",
        "contract_refs": ["amendment 4"],
        "assertion_strength": "ABSOLUTE",
        "specimen_role_map": {'AN-A01': 'sample-01', 'AN-A05': 'sample-02', 'AN-A07': 'sample-03', 'AN-A10': 'sample-04', 'AN-A14': 'sample-05', 'AN-A08': 'sample-06', 'AN-A09': 'control-01', 'AN-A12': 'control-02', 'AN-A11': 'control-03', 'AN-A05B': 'control-04'},
        "notes": "Anchor values are transcribed from "
                 "docs/ANCHORS.md and must match exactly.",
        "payload": payload,
        "anchor_assertions": assertions,
        "expected": {"semantic_lights": [], "mechanical_lights": [],
                     "cross_light": {"A_all": False, "A_vector": [False] * 3,
                                     "c3": "WITHHELD_NOT_IMPLEMENTED",
                                     "pooled_verdict_absent": True}},
        "oracle_point_expectations": oracle_expectations(payload),
        "replicate_classification": classify_n(payload),
    }
    return [entry]


def write_panel(panel, subdirectory):
    directory = os.path.join(FIXTURE_ROOT, "scenarios", subdirectory)
    if not os.path.isdir(directory):
        os.makedirs(directory)
    written = []
    for entry in panel:
        path = os.path.join(directory, entry["scenario_id"] + ".json")
        with open(path, "w") as handle:
            json.dump(entry, handle, indent=2, sort_keys=True)
            handle.write("\n")
        written.append(path)
    return written


def main():
    written = write_panel(build_clean_panel(), "clean")
    written += write_panel(build_anchor_panel(), "anchors")
    for path in written:
        print(os.path.relpath(path, FIXTURE_ROOT))
    print("scenarios written: %d" % len(written))


if __name__ == "__main__":
    main()
